// Bundles each MCP Apps iframe app (src/app-src/<name>.ts + the ext-apps client)
// into a single self-contained HTML string, emitted as a generated .ts module so
// the stdio server can serve it inline from a `ui://` resource with no runtime
// file reads. Runs before tsup/tsc (see package.json).
import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** @type {{ name: string, entry: string, exportName: string, title: string }[]} */
const apps = [
  { name: "hello", entry: "src/app-src/hello.ts", exportName: "HELLO_APP_HTML", title: "Lane" },
];

/** Wrap the bundled IIFE + card markup into one standalone HTML document. */
function pageHtml(title, scriptJs) {
  // Guard against the bundle containing a literal </script> that would close the tag early.
  const safeJs = scriptJs.replace(/<\/script>/gi, "<\\/script>");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="color-scheme" content="light dark" />
<style>
  :root { color-scheme: light dark; }
  body { margin: 0; font-family: -apple-system, "Segoe UI", system-ui, sans-serif; background: transparent; color: #201f2b; }
  .card { max-width: 460px; margin: 16px auto; padding: 20px 22px; border: 1px solid #e0dbf0; border-radius: 16px; background: #fff; box-shadow: 0 10px 30px rgb(39 28 60 / .08); }
  .badge { display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 999px; background: #efeaff; color: #5b43c9; font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
  h1 { margin: 12px 0 6px; font-size: 18px; letter-spacing: -.01em; }
  p { margin: 0; color: #6b6678; font-size: 13px; line-height: 1.5; }
  .ok { color: #2f9e6a; font-weight: 700; }
</style>
</head>
<body>
  <div class="card">
    <span class="badge">${title}</span>
    <h1>Interactive UI is <span class="ok">live</span></h1>
    <p id="data">Connecting to Lane…</p>
  </div>
<script>${safeJs}</script>
</body>
</html>`;
}

for (const app of apps) {
  const result = await build({
    entryPoints: [path.join(root, app.entry)],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: true,
    write: false,
  });
  const js = result.outputFiles[0].text;
  const html = pageHtml(app.title, js);
  const outPath = path.join(root, "src/generated", `${app.name}-app.ts`);
  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(
    outPath,
    `// AUTO-GENERATED by scripts/build-apps.mjs — do not edit by hand.\nexport const ${app.exportName} = ${JSON.stringify(html)};\n`,
  );
  console.error(`[build-apps] ${app.name}: ${(html.length / 1024).toFixed(1)} KB -> ${path.relative(root, outPath)}`);
}
